version: '3.8'

services:
  # Backend API
  backend:
    build: .
    container_name: marketpulse-backend
    ports:
      - "8000:8000"
    environment:
      # Add your API keys here or use .env file
      - FINNHUB_API_KEY=${FINNHUB_API_KEY:-}
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY:-}
      - GNEWS_API_KEY=${GNEWS_API_KEY:-}
      - NEWS_API_KEY=${NEWS_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/v1/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - marketpulse-network

  # Frontend (React) - Optional for production
  frontend:
    image: node:18-alpine
    container_name: marketpulse-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - marketpulse-network
    profiles:
      - dev  # Only start with --profile dev

networks:
  marketpulse-network:
    driver: bridge

# Optional: Add Redis for production caching
# volumes:
#   redis_data: