apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketpulse-backend
  labels:
    app: marketpulse
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: marketpulse
      component: backend
  template:
    metadata:
      labels:
        app: marketpulse
        component: backend
    spec:
      containers:
      - name: backend
        image: marketpulse-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: FINNHUB_API_KEY
          valueFrom:
            secretKeyRef:
              name: marketpulse-secrets
              key: finnhub-api-key
              optional: true
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: marketpulse-secrets
              key: gemini-api-key
              optional: true
        - name: GNEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: marketpulse-secrets
              key: gnews-api-key
              optional: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL