# Template for Kubernetes secrets
# DO NOT commit actual secrets to git!
# 
# Usage:
# 1. Copy this file: cp secrets-template.yaml secrets.yaml
# 2. Replace placeholder values with base64 encoded API keys:
#    echo -n "your_api_key" | base64
# 3. Apply: kubectl apply -f secrets.yaml
# 4. Add secrets.yaml to .gitignore

apiVersion: v1
kind: Secret
metadata:
  name: marketpulse-secrets
  labels:
    app: marketpulse
type: Opaque
data:
  # Base64 encoded API keys (optional - system works without them)
  finnhub-api-key: "your_base64_encoded_finnhub_key_here"
  gemini-api-key: "your_base64_encoded_gemini_key_here"
  gnews-api-key: "your_base64_encoded_gnews_key_here"
  alpha-vantage-api-key: "your_base64_encoded_alpha_vantage_key_here"
  news-api-key: "your_base64_encoded_news_api_key_here"

# Example of encoding:
# echo -n "your_actual_api_key" | base64